server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qr_game
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: qr_game
  thymeleaf:
    encoding: UTF-8
#    prefix: /
#    suffix: .html
#  resources:
#    chain:
#      strategy:
#        fixed:
#          enabled: true
#          paths: /**
#          version: v12